#################################################################################################################################
#### 네이버 증권 종목분석 리포트 수집 generated by Comet
#################################################################################################################################

library(rvest)
library(httr)
library(dplyr)

url <- "https://finance.naver.com/research/company_list.naver?page=1"

# 네이버 페이지 인코딩에 맞춰 GET 요청 보내고 내용 읽기
res <- GET(url, user_agent("Mozilla/5.0"))
content_raw <- content(res, as="text", encoding="EUC-KR")
page <- read_html(content_raw)

# 테이블 읽기
report_table <- page %>%
  html_node("table.type_1") %>%
  html_table(fill=TRUE)

# 링크는 직접 추출
links <- page %>%
  html_nodes("table.type_1 tr td a") %>%
  html_attr("href")
# 제목에 해당하는 링크만 추출
report_links <- links[grepl("read.naver", links)]
report_links <- paste0("https://finance.naver.com", report_links)

# PDF 링크 추출 (없을 수도 있음)
pdf_links <- page %>%
  html_nodes("table.type_1 tr td a") %>%
  html_attr("href") %>%
  .[grepl("\\.pdf$", .)]

# 데이터 정제: 테이블에서 불필요한 행(헤더 등) 제거
report_table <- report_table %>%
  filter(종목명 != "")

# 링크와 테이블을 결합
report_table$제목링크 <- report_links[1:nrow(report_table)]

# View(report_table)로 확인 가능
print(report_table)

# 필요한 경우 엑셀 저장
# install.packages("writexl")
# writexl::write_xlsx(report_table, "naver_reports
